security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
server:
  port: 8761
eureka:
  client:
    healthcheck:  # 健康检查 health
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka